### ISSUE TITLE
Version 0.3.3 won't compile with `create-react-app`.

### ISSUE THREAD

**Issue by hubbardp** [usnistgov/jsfive#21]
Using version 0.3.3 in a site created with `create-react-app` (https://github.com/facebook/create-react-app) causes a compilation error, as in this simple example:

1. `$ npx create-react-app test-jsfive`
2. `$ cd test-jsfive`
3. `$ npm install jsfive@0.3.3`
4. Add to `src/App.js`:
```
	import * as hdf5 from 'jsfive';
```
5. `$ npm start`
```
Failed to compile.
./node_modules/jsfive/esm/high-level.js 30:8
Module parse failed: Unexpected token (30:8)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|    * @member {Array<string>} _keys;
|    */
>   parent;
|   file;
|   name;
```

Version 0.2.3 does work, however (i.e., replace step 3 with `$ npm install jsfive@0.2.3` and there is no error at step 5).

**Comment by bmaranville** [comment]
Ah... I added some declarations of public class members, which is probably not supported without plugins in babel.  I could certainly remove them, as they are mostly for type hinting for debugging.

**Comment by bmaranville** [comment]
Can you try installing the git version with 
```
npm install git+https://github.com/usnistgov/jsfive.git
```
and see if the change I just made fixes your problem?

**Comment by hubbardp** [comment]
Now I seem to get a different error.  I started over with a new project, and used `npm install git+https://github.com/usnistgov/jsfive.git` as step 3.  Now in step 5 I get:

```
Failed to compile.

./node_modules/jsfive/dist/hdf5.js 1998:16
Module parse failed: Unexpected token (1998:16)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|
|   class Rt extends Ft {
>     B_LINK_NODE = new Map([["signature", "4s"], ["node_type", "B"], ["node_level", "B"], ["entries_used", "H"], ["left_sibling", "Q"], ["right_sibling", "Q"]]);
|
|     _read_node_header(e, t) {
```

**Comment by bmaranville** [comment]
I had forgotten about those.  I am actually using those class properties in the logic, so I can't just comment them out (they define constants for the class).

Could you try installing this babel plugin to support loading this type of class? https://babeljs.io/docs/en/babel-plugin-proposal-class-properties

**Comment by bmaranville** [comment]
I think you might also be able to use the precompiled version with
```
const hdf5 = require("jsfive");
```
instead of using the import statement

**Comment by hubbardp** [comment]
It appears that `@babel/plugin-proposal-class-properties` (https://babeljs.io/docs/en/babel-plugin-proposal-class-properties) requires a custom Babel config file.  It does not look like that is supported by `create-react-app`:

https://github.com/facebook/create-react-app/issues/4648#issuecomment-398540069

That particular comment is from 2018, but it does not appear that the situation has changed.

**Comment by bmaranville** [comment]
Thanks for checking.  I am surprised it's breaking things, as class properties are supported in nodejs and every browser except IE.  They don't even need to be transformed by babel, they could be passed right through unchanged.

When I have a few spare moments I'll look into moving the constants into the init or constructor, instead of attaching to the class.

**Comment by bmaranville** [comment]
I realized that I can do the transforms myself when building the compiled version... after the latest commit fb8658a9c5624500a9f433254a3c3634b834ffcc I was able to start a react app with the recipe you provided above, so I think it's fixed.  If you find that it is working, I might do another release soon so that it can be installed from npm.

**Comment by hubbardp** [comment]
Thanks.  With that change, my simple example does work for me, too.

But now I am having another problem when I try that change in a real application.  I have the following code for a file input:
```
const file = event.target.files[0];
const filename = file.name;
const reader = new FileReader();
reader.onloadend = (event) => { 
  const buffer = event.target.result;
  const fileHdf5 = new hdf5.File(buffer, filename);
  // ...
}
reader.readAsArrayBuffer(file);
```

The `new hdf5.File(...)` code now gives an exception:
```
TypeError: jsfive__WEBPACK_IMPORTED_MODULE_1__.File is not a constructor
```

**Comment by bmaranville** [comment]
I think I found a workaround... though I'm not sure why.  If you explicitly import the module built for node (commonjs) it seems to work.  Instead of 
```js
import * as hdf5 from 'jsfive';
```
try
```js
import * as hdf5 from 'jsfive/dist/index.js';
```

**Comment by hubbardp** [comment]
Thanks,.  Using `npm install git+https://github.com/usnistgov/jsfive.git` then `import * as hdf5 from 'jsfive/dist/index.js';` does seem to work for me, too.

The `import` statement looks odd, though, and does not feel like a permanent solution.  I am not familiar with `parcel`, but I wonder if the way it is being used to build the NPM module could be improved?  Perhaps the following is related?

https://github.com/parcel-bundler/parcel/issues/504#issuecomment-412352152

**Comment by bmaranville** [comment]
I think it will look less awkward to use 
```js
const hdf5 = require("jsfive");
``` 
(which I just verified works with the git version of jsfive and ```create-react-app```) instead of 
```js
import * as hdf5 from 'jsfive/dist/index.js';
```
I was a bit thrown off by the way ```create-react-app``` allows import statements without paths or file extensions (.js or .mjs) but in the end they are using webpack to compile ES6 sources if you use an import statement - the two statements above should have an equivalent effect, since "main" in the package.json is pointing to "dist/index.js" and that is what you will get if you use ```require```.

The ```require``` approach doesn't work with the released jsfive@0.3.3 because I hadn't added the class-properties transform to the node build at that time.  I will make a new release shortly that should work directly with ```require```.

**Comment by bmaranville** [comment]
Version 0.3.5 has been published on npm - I hope it works for you.

**Comment by hubbardp** [comment]
Thanks.  I did `npm install jsfive` and got 0.3.5, and the following does indeed compile:
```
const hdf5 = require('jsfive');
```
But then it does not work to execute something like the following:
```
const fileHdf5 = new hdf5.File(buffer, filename);
```
I get an exception:
```
Uncaught TypeError: hdf5.File is not a constructor
```
So I guess I have to stick with the more awkward-looking import:
```
import * as hdf5 from 'jsfive/dist/index.js';
```

**Comment by bmaranville** [comment]
My apologies - I tested that ```hdf5``` was an object in the browser after ```require('jsfive')``` in App.js, and that in the browser react app you can call ```new hdf5.File```, but I didn't check that it would work in the app code itself.  

I will keep this ticket open.

**Comment by hubbardp** [comment]
I did find that I can shorten the statement to this:
```
import * as hdf5 from 'jsfive/dist';
```
Probably that  would be good enough, assuming it is documented on the main `README.md` somewhere.

**Comment by bmaranville** [comment]
I did do a bit more digging because I was confused as to what was happening... it looks like ```create-react-app``` is actually grabbing the browser library "dist/hdf5.js" if you do ```require('jsfive');``` which is not what I was expecting.  If you do the same thing in nodejs it grabs "dist/index.js" like it is supposed to do.

The upside (or downside?) is that the browser library defines hdf5 on the global scope, so that you can do 
```js
require('jsfive');
// at this point window.hdf5 is defined!
hdf5File = new hdf5.File(buffer, filename);
```

This is also unsatisfying, though, and I think I'll update ```README.md``` to use the import statement you suggest above.

I still find it odd that the official documentation for CRA [strongly encourages you to use ES6 imports, and even explicitly states that class fields are a supported feature](https://create-react-app.dev/docs/supported-browsers-features#supported-language-features) within the CRA app code, but apparently that combination is not supported in libraries that are imported.

**Comment by hubbardp** [comment]
This `import * as hdf5 from 'jsfive/dist';` approach has been working for me, and is now documented, so I think we can close this issue.  Thanks for addressing it.
