### ISSUE TITLE
Npm version 0.3.8 has an issue when resolving imports

### ISSUE THREAD

**Issue by MrTeej** [usnistgov/jsfive#29]
When installing latest jsfive, there's an issue with one of the imports inside the filters file.

./node_modules/jsfive/esm/filters.js
Module not found: Can't resolve '../node_modules/pako/dist/pako.esm.mjs'

**Comment by bmaranville** [comment]
I'm having trouble reproducing the error (`npm install jsfive` works in node 14 and 16 for me) - can you provide the steps required to reproduce?

**Comment by MrTeej** [comment]
Sorry I should've mentioned it fails when we try to run the project that jsfive is imported to.

Just a basic >` npm run start` (hooked up to our craco inside package.json) 
-> `"start": "ENV=local PUBLIC_URL=/ craco start",`

**Comment by bmaranville** [comment]
I wonder, are you loading the jsfive library directly from source, e.g.  `jsfive/esm/high_level.js` in your project?  This will probably no longer work.  Importing from `jsfive/dist/index.js` should work if you want to use a relative path, and this is still an ESM module (but it has the pako library bundled with it).  `import * as hdf5 from 'jsfive';` should also work in your app - please let me know if it doesn't.

I could rework Filters so that the unzipping library is an injected dependency, so that you could still import the source directly, but I wasn't sure how important it was to users to be able to directly import the source (particularly when an ESM module is now available in the `dist` folder)

**Comment by MrTeej** [comment]
Brilliant thanks, this works. 

We are using:
`import * as hdf5 from 'jsfive/dist/index.js';`
