### ISSUE TITLE
Question: Will all data be loaded as a single consecutive array?

### ISSUE THREAD

**Issue by Lauenburg** [usnistgov/jsfive#32]
I need to serve on-demand cropped 2D tiles from a 3D image volume for an application I am developing. Instead of saving each cropped 2D image as a PNG, I thought about directly cutting them from the corresponding h5 file.

I get a single, consecutive array using your library to read the data (1D array of length z\*y\*x).
**Is this the intended behavior meant by the sentence "It is only for reading HDF5 files as an ArrayBuffer representation of the file.", or is it possible to maintain a 3D array structure when loading?**

**Comment by bmaranville** [comment]
The caveat "...only for reading HDF5 files as an ArrayBuffer representation..." is only meant to apply to the initial load of the file e.g. ```f = new hdf5.File(ArrayBuffer);```

You are correct that jsfive can only return 1D arrays from a read operation - this is because there are no multidimensional arrays built-in to javascript.  There is also no "slice" capability built into jsfive, so you are only able to read entire datasets into an output Array.

If you want to be able to slice (retrieve a particular range of data in x,y,z) I suggest you use https://github.com/usnistgov/h5wasm instead of jsfive.  It is similar in its interface, and can also be installed with npm.  If you want it to automatically create nested arrays of the same shape as your slice, I recommend passing the output of a slice read to a matrix object from the mathjs library: https://mathjs.org/docs/datatypes/matrices.html

**Comment by Lauenburg** [comment]
Thank you so much! The information is extremely helpful.
