### ISSUE TITLE
Not available on npm?

### ISSUE THREAD

**Issue by pzi** [usnistgov/jsfive#7]
Hi, thanks for maintaining jsfive!

Quick question: how come this package is not available on NPM?
Are there any legal reasons for it to not be published?

Cheers & thanks again
Patrik

**Comment by bmaranville** [comment]
Hello - I'm glad the project has been useful to you.  For your use case, would publishing to github packages be sufficient?  That would be a straightforward way for me to make it available for npm installs.  I haven't done that before, so it may take me a little bit to figure out how to do it.

I would welcome your contributions if you would like to help!  Unfortunately these would have to be as pull requests because I cannot add people outside our (US Federal Agency) organization as collaborators on a project in the https://github.com/usnistgov/ group.
[https://avatars1.githubusercontent.com/u/5330158?s=280&v=4]<https://github.com/usnistgov/>
National Institute of Standards and Technology · GitHub<https://github.com/usnistgov/>
Dismiss Grow your team on GitHub. GitHub is home to over 40 million developers working together. Join them to grow your own development teams, manage permissions, and collaborate on projects.
github.com
Thanks! - Brian
________________________________

**Comment by pzi** [comment]
Hi Brian, 

Of course pull requests are fine. No need to be added to your organisation as collaborator.

In my case, I wanted to avoid having a dependency on a GitHub package/project because if the repository gets renamed/moved/changed/deleted, the app I am working on will fail to install & build. I will see what I can do to help with getting it on NPM.

Cheers
Patrik

**Comment by pzi** [comment]
Hi Brian,

Are you able to publish jsfive to Github packages for now please? (I noticed NPM has been acquired by GitHub recently).

Regards & thanks
Patrik

**Comment by bmaranville** [comment]
Hi, Patrik.  I have published the package to github packages.  Please see https://github.com/usnistgov/jsfive/packages

**Comment by bmaranville** [comment]
Note that you have to authenticate to github before you can install these... I was unaware of this restriction.  See discussion at https://github.community/t5/GitHub-API-Development-and/Download-from-Github-Package-Registry-without-authentication/td-p/35255

**Comment by bmaranville** [comment]
I'm having trouble getting the package to publish properly.

**Comment by pzi** [comment]
Not sure if it helps your situation, but I found this tool quite helpful with publishing packages: https://github.com/sindresorhus/np

This should also make it simpler to publish it to NPM if you would still consider that.

**Comment by bmaranville** [comment]
Thanks, Patrik - I think we are encountering a bug in github, though - something other people have experienced also, related to billing of data output (which shouldn't apply to public repositories which have free data, hence it is a billing bug).  I was able to publish in a test fork in a different organization with the same settings, and it worked fine.  Hopefully the bug will be fixed soon, and I will re-publish.

**Comment by obermillerk** [comment]
What is preventing this from being properly published on npm? I'd rather not have to deal with a second package registry, and the github registry requiring authentication to pull packages complicates things even more.

**Comment by bmaranville** [comment]
github has an internal bug.  They are unable to publish packages for public repositories in some cases for organizations that have legacy billing (which makes it impossible to publish private packages but should not affect public repos).  They are supposed to be working on it (for the last several months)
With given externalities they have warned that things take longer than usual to fix.

I was also hoping they would remove the need to authenticate to pull packages, but that's not happening anytime soon as far as I can tell.

I think I will give up on the github package repo at this point and I will try to make it available in another way.
________________________________

**Comment by obermillerk** [comment]
That doesn't really answer the part about releasing it properly on npm. I would think it'd be easier just to npm publish it, and then it's available as people would normally expect

**Comment by bmaranville** [comment]
Yes, the "other way" I mentioned is npm.  I will be working on that.
________________________________

**Comment by obermillerk** [comment]
In the meantime, would it be possible to make a tag for the 0.2.0 release in the repository that seems to be on github packages?

**Comment by bmaranville** [comment]
The release is still not working on github packages... the download link is broken, so there's no way to install from github even if you authenticate.

**Comment by obermillerk** [comment]
If you just tag the commit I can reference that and circumvent github packages entirely and point it to the github repository. The last tag I see presently is 0.1.6

**Comment by bmaranville** [comment]
Ah I'm glad you can work around it! 

I just made a release 0.2.1 that matches the package.json version information.  Sorry for all the version churn.  Nothing really changed since release 0.1.6 but iIt took me quite a while to figure out what was going on with the package system on github.  I didn't believe that it was just broken for a while.

**Comment by obermillerk** [comment]
Much appreciated, as are the quick responses!

**Comment by bmaranville** [comment]
package has been published to npm

**Comment by pzi** [comment]
Great outcome, thanks @bmaranville :tada:
